### ISSUE TITLE
non-ssl port

### ISSUE THREAD

**Issue by sgohl** [garywiz/docker-keybox#2]
Hi,
I can't really simple get it working without ssl.
How can I run this keybox image so that it just listens on plain HTTP?

I got an nginx before, which handles the SSL...

**Comment by garywiz** [comment]
Yes, you're correct.  This is now fixed.

To try it, first get the launcher file:

```
docker run -i garywiz/docker-keybox --task get-launcher | sh
```

Then, look in the launcher file (called run-docker-keybox.sh) and you'll see comments about
how to enable the HTTP server.  Basically, you need to pass a blank `CONFIG_EXT_SSL_HOSTNAME` and the chosen port as environment variables.

I've tested this and it seems to work.  Please confirm if it does for you.  Thanks!
